package com.traffic.scenario;

import java.util.*;

/**
 * Exports generated scenarios to MATLAB-compatible formats.
 * Supports: MATLAB .m scripts, RoadRunner scene files, structured JSON.
 */
public class MatlabExportService {

    public String exportToMatlabScript(ScenarioBuilder.GeneratedScenario scenario) {
        StringBuilder m = new StringBuilder();
        m.append("%% Indian Road Scenario — Auto-Generated\n");
        m.append("%% Generated by TrafficSim Scenario Generator\n");
        m.append(String.format("%% Seed: %d | City: %s\n", scenario.usedSeed, scenario.config.cityPreset));
        m.append(String.format("%% Date: %s\n\n", new Date().toString()));
        m.append("clear; clc; close all;\n\n");

        // Road Network
        m.append("%% ========== ROAD NETWORK ==========\n");
        m.append(String.format("numRoads = %d;\n", scenario.roads.size()));
        m.append(String.format("numIntersections = %d;\n\n", scenario.intersections.size()));

        // Intersections
        m.append("% Intersection positions [x, y]\n");
        m.append("intersections = [\n");
        for (ScenarioBuilder.ScenarioIntersection si : scenario.intersections) {
            m.append(String.format("    %.1f, %.1f;  %% ID %d%s\n",
                si.x, si.y, si.id, si.hasSignal ? " (signalized)" : ""));
        }
        m.append("];\n\n");

        // Roads
        m.append("% Road connections [srcId, dstId, width, speedLimit, lanes]\n");
        m.append("roads = [\n");
        for (ScenarioBuilder.ScenarioRoad r : scenario.roads) {
            m.append(String.format("    %d, %d, %.1f, %.1f, %d;  %% %s\n",
                r.srcId, r.dstId, r.width, r.speedLimit, r.lanes, r.name));
        }
        m.append("];\n\n");

        // Create driving scenario (MATLAB Automated Driving Toolbox)
        m.append("%% ========== DRIVING SCENARIO ==========\n");
        m.append("scenario = drivingScenario;\n\n");

        // Add roads
        m.append("% Add road segments\n");
        for (ScenarioBuilder.ScenarioRoad r : scenario.roads) {
            m.append(String.format(
                "roadCenters = [%.1f %.1f 0; %.1f %.1f 0];\n",
                r.srcX, r.srcY, r.dstX, r.dstY));
            m.append(String.format("road(scenario, roadCenters, 'Lanes', lanespec(%d), 'Name', '%s');\n\n",
                r.lanes, r.name != null ? r.name.replace("'", "") : "Road"));
        }

        // Vehicles
        m.append("%% ========== VEHICLES ==========\n");
        m.append(String.format("numVehicles = %d;\n\n", scenario.vehicles.size()));

        String[] vehicleColors = {"[0.2 0.6 1.0]", "[1.0 0.8 0.0]", "[0.0 0.8 0.4]", "[1.0 0.3 0.3]", "[0.6 0.6 0.6]"};
        int colorIdx = 0;
        for (ScenarioBuilder.ScenarioVehicle v : scenario.vehicles) {
            double len = getVehicleLength(v.type);
            double wid = getVehicleWidth(v.type);
            m.append(String.format(
                "v%d = vehicle(scenario, 'ClassID', 1, 'Position', [%.1f %.1f 0], " +
                "'Length', %.1f, 'Width', %.1f); %% %s (%s)\n",
                v.id, v.x, v.y, len, wid, v.type, v.behavior));
            colorIdx = (colorIdx + 1) % vehicleColors.length;
        }
        m.append("\n");

        // Obstacles
        m.append("%% ========== OBSTACLES ==========\n");
        for (ScenarioBuilder.ScenarioObstacle obs : scenario.obstacles) {
            m.append(String.format(
                "barrier(scenario, 'Position', [%.1f %.1f 0], 'Width', %.1f, 'Length', %.1f); %% %s\n",
                obs.x, obs.y, obs.width, obs.height, obs.type));
        }
        m.append("\n");

        // Road conditions as annotations
        m.append("%% ========== ROAD CONDITIONS ==========\n");
        m.append("% Stored as metadata for custom processing\n");
        m.append("conditions = struct();\n");
        int ci = 1;
        for (ScenarioBuilder.ScenarioCondition c : scenario.conditions) {
            m.append(String.format(
                "conditions(%d).type = '%s'; conditions(%d).position = [%.1f %.1f]; " +
                "conditions(%d).severity = %.2f; conditions(%d).radius = %.1f;\n",
                ci, c.type, ci, c.x, c.y, ci, c.severity, ci, c.radius));
            ci++;
        }
        m.append("\n");

        // Visualization
        m.append("%% ========== VISUALIZATION ==========\n");
        m.append("figure('Name', 'Indian Road Scenario', 'Color', [0.1 0.1 0.1]);\n");
        m.append("plot(scenario);\n");
        m.append("title(sprintf('Scenario: %s (Seed: %d)'), 'Color', 'w');\n");
        m.append("set(gca, 'Color', [0.15 0.15 0.15], 'XColor', 'w', 'YColor', 'w');\n\n");
        m.append("disp('Scenario loaded successfully.');\n");
        m.append(String.format("disp('  Roads: %d');\n", scenario.roads.size()));
        m.append(String.format("disp('  Vehicles: %d');\n", scenario.vehicles.size()));
        m.append(String.format("disp('  Obstacles: %d');\n", scenario.obstacles.size()));
        m.append(String.format("disp('  Conditions: %d');\n", scenario.conditions.size()));

        return m.toString();
    }

    public String exportToRoadRunnerScene(ScenarioBuilder.GeneratedScenario scenario) {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<RoadRunnerScene version=\"1.0\">\n");
        sb.append("  <Metadata>\n");
        sb.append(String.format("    <Generator>TrafficSim v1.0</Generator>\n"));
        sb.append(String.format("    <Seed>%d</Seed>\n", scenario.usedSeed));
        sb.append(String.format("    <City>%s</City>\n", scenario.config.cityPreset));
        sb.append("  </Metadata>\n");

        sb.append("  <Roads>\n");
        for (ScenarioBuilder.ScenarioRoad r : scenario.roads) {
            sb.append(String.format(
                "    <Road id=\"%d\" lanes=\"%d\" width=\"%.1f\">\n" +
                "      <Start x=\"%.1f\" y=\"%.1f\" />\n" +
                "      <End x=\"%.1f\" y=\"%.1f\" />\n" +
                "    </Road>\n", r.id, r.lanes, r.width, r.srcX, r.srcY, r.dstX, r.dstY));
        }
        sb.append("  </Roads>\n");

        sb.append("  <Actors>\n");
        for (ScenarioBuilder.ScenarioVehicle v : scenario.vehicles) {
            sb.append(String.format(
                "    <Vehicle id=\"%d\" type=\"%s\" x=\"%.1f\" y=\"%.1f\" speed=\"%.1f\" />\n",
                v.id, v.type, v.x, v.y, v.speed));
        }
        sb.append("  </Actors>\n");

        sb.append("</RoadRunnerScene>\n");
        return sb.toString();
    }

    private double getVehicleLength(String type) {
        switch (type) {
            case "CAR": return 4.5;
            case "BIKE": return 2.0;
            case "AUTO_RICKSHAW": return 3.0;
            case "BUS": return 12.0;
            case "TRUCK": return 10.0;
            default: return 4.0;
        }
    }

    private double getVehicleWidth(String type) {
        switch (type) {
            case "CAR": return 2.0;
            case "BIKE": return 0.8;
            case "AUTO_RICKSHAW": return 1.5;
            case "BUS": return 2.5;
            case "TRUCK": return 2.5;
            default: return 2.0;
        }
    }
}
